version: '3'
services:
  my-mongoDB:
<<<<<<< HEAD
    image: mongo:3.4.8
=======
    image: mongo:3
>>>>>>> 1125c07 (Feature/spring boot mongo kotlin)
    ports:
      - "27017:27017"
    volumes:
      - data-db:/data/db
      - mongo-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
volumes:
  data-db:
  mongo-config: