version: '3'
services:
  database:
    image: 'postgres:13.3'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: default_database # The PostgreSQL default database (automatically created at first launch)
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
  db-my-sql:
    image: 'mysql:5.7'
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'bank'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./db-data-mysql/:/var/lib/mysql